services:
  bot:
    build:
      context: .
    container_name: tg_bot1
    init: true
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_PATH: data/bot.db
    volumes:
      - bot_data:/app/data
    command: ["python", "-m", "app.main"]

volumes:
  bot_data:
